version: 0.0
os: linux
files:
  - source: https://s3-us-west-2.amazonaws.com/binit-a1ecommerce-tomcat-deploy-bucket-final/a1ecommerce.war
    destination: /opt/apache-tomcat-7.0.78/webapps/
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 10000 
